set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256color:RGB"

# Unbind default prefix
unbind C-b

# Set new prefix to Ctrl+Space
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on
# Mouse selection: copy but stay in copy mode
bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-selection
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection

set -g focus-events on
set -g status-position bottom

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

set -g @yank_action 'copy-pipe'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @vim_navigator_mapping_left "C-h"
set -g @vim_navigator_mapping_right "C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

set -g status-right ""
# set -ag status-right "#{E:@catppuccin_status_application}"
# set -ag status-right "#{E:@catppuccin_status_window}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
# Customize the date/time format (default is %Y-%m-%d %H:%M)
set -g @catppuccin_date_time_text " %H:%M"
set -ag status-right "#{E:@catppuccin_status_date_time}"
# set -ogq @catppuccin_window_flags_icon_zoom "   "
# set -g @catppuccin_window_icons_enabled on

set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"

# Yank set vi-mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# Same as 'q'
# Bind Escape to cancel copy-mode (C-[ is mapped to Escape)
bind-key -T copy-mode-vi Escape send-keys -X cancel

# Always use cwd
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# tmux sessionizer
bind C-o display-popup -E "tms"
bind C-j display-popup -E "tms switch"
bind C-w display-popup -E "tms windows"
bind C-r "run-shell 'tms refresh'"
bind C-k confirm -p "Kill current session? (y/N):" "run-shell 'tms kill'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
